"""initial schema

Revision ID: 843a71272e9f
Revises: 
Create Date: 2026-07-27 03:01:43.397334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.base


# revision identifiers, used by Alembic.
revision: str = '843a71272e9f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('municipality', sa.String(length=150), nullable=True),
    sa.Column('district', sa.String(length=150), nullable=True),
    sa.Column('street', sa.String(length=200), nullable=True),
    sa.Column('normalized_street', sa.String(length=200), nullable=True),
    sa.Column('house_number', sa.String(length=20), nullable=True),
    sa.Column('house_number_suffix', sa.String(length=10), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('precision', sa.Enum('EXACT_ADDRESS', 'STREET_LEVEL', 'BLOCK_LEVEL', 'DISTRICT_LEVEL', 'UNKNOWN', name='location_precision'), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', app.models.base.GUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('payload', app.models.base.JSONVariant(), nullable=True),
    sa.Column('performed_by', sa.String(length=200), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
    op.create_table('investment_policies',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('strategy', sa.String(length=50), nullable=False),
    sa.Column('is_screening_default', sa.Boolean(), nullable=False),
    sa.Column('max_purchase_price_cents', sa.Integer(), nullable=True),
    sa.Column('max_all_in_cost_cents', sa.Integer(), nullable=True),
    sa.Column('min_data_confidence', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('include_water_damage_objects', sa.Boolean(), nullable=False),
    sa.Column('include_land_development', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_versions',
    sa.Column('engine_name', sa.String(length=100), nullable=False),
    sa.Column('version_label', sa.String(length=50), nullable=False),
    sa.Column('calibration_period_start', sa.Date(), nullable=True),
    sa.Column('calibration_period_end', sa.Date(), nullable=True),
    sa.Column('validated_against_history', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('quality_class', sa.Enum('OFFICIAL_PRIMARY', 'OFFICIAL_AGGREGATE', 'TRANSACTION_VERIFIED', 'COMMERCIAL_LICENSED', 'COMMERCIAL_PORTAL', 'USER_SUPPLIED', 'DOCUMENT_INTELLIGENCE', 'AI_INFERENCE', name='source_quality_class'), nullable=False),
    sa.Column('access_type', sa.Enum('PUBLIC', 'REGISTRATION_REQUIRED', 'LICENSE_REQUIRED', 'MANUAL_IMPORT', name='source_access_type'), nullable=False),
    sa.Column('geographic_scope', sa.String(length=200), nullable=False),
    sa.Column('content_description', sa.Text(), nullable=False),
    sa.Column('is_official', sa.Boolean(), nullable=False),
    sa.Column('direct_access_enabled', sa.Boolean(), nullable=False),
    sa.Column('direct_access_disabled_reason', sa.Text(), nullable=True),
    sa.Column('health_status', sa.String(length=30), nullable=False),
    sa.Column('last_successful_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('license_notes', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('properties',
    sa.Column('primary_address_id', app.models.base.GUID(), nullable=False),
    sa.Column('property_type', sa.Enum('CONDOMINIUM_UNIT', 'SINGLE_FAMILY_HOUSE', 'MULTI_FAMILY_HOUSE', 'LAND_PARCEL', 'COMMERCIAL', 'FORECLOSURE', 'OTHER', name='property_type'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['primary_address_id'], ['addresses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_permissions',
    sa.Column('source_id', app.models.base.GUID(), nullable=False),
    sa.Column('license_required', sa.Boolean(), nullable=False),
    sa.Column('usage_notes', sa.Text(), nullable=False),
    sa.Column('verified_at', sa.Date(), nullable=True),
    sa.Column('verified_by', sa.String(length=200), nullable=True),
    sa.Column('lawful_automated_access_confirmed', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_records',
    sa.Column('source_id', app.models.base.GUID(), nullable=False),
    sa.Column('external_id', sa.String(length=300), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_date', sa.Date(), nullable=True),
    sa.Column('valuation_date', sa.Date(), nullable=True),
    sa.Column('raw_payload', app.models.base.JSONVariant(), nullable=True),
    sa.Column('import_method', sa.String(length=50), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actual_project_results',
    sa.Column('property_id', app.models.base.GUID(), nullable=False),
    sa.Column('actual_purchase_price_cents', sa.Integer(), nullable=True),
    sa.Column('actual_acquisition_costs_cents', sa.Integer(), nullable=True),
    sa.Column('actual_renovation_costs_cents', sa.Integer(), nullable=True),
    sa.Column('actual_project_duration_days', sa.Integer(), nullable=True),
    sa.Column('actual_sale_price_cents', sa.Integer(), nullable=True),
    sa.Column('actual_achieved_rent_cents', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('buildings',
    sa.Column('property_id', app.models.base.GUID(), nullable=False),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('year_built_status', sa.Enum('VERIFIED', 'DOCUMENTED', 'OBSERVED', 'DERIVED', 'ESTIMATED', 'INFERRED', 'UNKNOWN', 'CONFLICTING', 'NOT_APPLICABLE', name='year_built_status'), nullable=False),
    sa.Column('year_built_source_record_id', app.models.base.GUID(), nullable=True),
    sa.Column('modernization_year', sa.Integer(), nullable=True),
    sa.Column('floor_count', sa.Integer(), nullable=True),
    sa.Column('has_elevator', sa.Boolean(), nullable=True),
    sa.Column('is_monument_protected', sa.Boolean(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['year_built_source_record_id'], ['source_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cost_library_items',
    sa.Column('trade', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('profile_type', sa.String(length=20), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('unit_price_cents', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('source_record_id', app.models.base.GUID(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_points',
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', app.models.base.GUID(), nullable=False),
    sa.Column('field_name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.Enum('VERIFIED', 'DOCUMENTED', 'OBSERVED', 'DERIVED', 'ESTIMATED', 'INFERRED', 'UNKNOWN', 'CONFLICTING', 'NOT_APPLICABLE', name='data_status'), nullable=False),
    sa.Column('value_type', sa.Enum('MONEY_CENTS', 'DECIMAL', 'INTEGER', 'TEXT', 'BOOLEAN', 'DATE', 'JSON', name='value_type'), nullable=False),
    sa.Column('value_numeric', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('value_int', sa.Integer(), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_bool', sa.Boolean(), nullable=True),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('value_json', app.models.base.JSONVariant(), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('source_record_id', app.models.base.GUID(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('confidence_breakdown', app.models.base.JSONVariant(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_by', sa.String(length=200), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('superseded_by_id', app.models.base.GUID(), nullable=True),
    sa.Column('supersedes_reason', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['data_points.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_points_entity_id'), 'data_points', ['entity_id'], unique=False)
    op.create_index(op.f('ix_data_points_entity_type'), 'data_points', ['entity_type'], unique=False)
    op.create_index(op.f('ix_data_points_field_name'), 'data_points', ['field_name'], unique=False)
    op.create_index(op.f('ix_data_points_is_current'), 'data_points', ['is_current'], unique=False)
    op.create_table('due_diligence_items',
    sa.Column('property_id', app.models.base.GUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('criticality', sa.String(length=20), nullable=False),
    sa.Column('depends_on_calculation', sa.String(length=200), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finance_scenarios',
    sa.Column('property_id', app.models.base.GUID(), nullable=True),
    sa.Column('equity_cents', sa.Integer(), nullable=True),
    sa.Column('loan_amount_cents', sa.Integer(), nullable=True),
    sa.Column('interest_rate_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('amortization_rate_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('fixed_rate_years', sa.Integer(), nullable=True),
    sa.Column('is_market_reference_only', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('geo_locations',
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', app.models.base.GUID(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('precision', sa.Enum('EXACT_ADDRESS', 'STREET_LEVEL', 'BLOCK_LEVEL', 'DISTRICT_LEVEL', 'UNKNOWN', name='geo_precision'), nullable=False),
    sa.Column('source_record_id', app.models.base.GUID(), nullable=True),
    sa.Column('captured_at', sa.Date(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geo_locations_entity_id'), 'geo_locations', ['entity_id'], unique=False)
    op.create_index(op.f('ix_geo_locations_entity_type'), 'geo_locations', ['entity_type'], unique=False)
    op.create_table('investment_scenarios',
    sa.Column('property_id', app.models.base.GUID(), nullable=False),
    sa.Column('investment_policy_id', app.models.base.GUID(), nullable=True),
    sa.Column('strategy', sa.String(length=50), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investment_policy_id'], ['investment_policies.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('land_parcels',
    sa.Column('property_id', app.models.base.GUID(), nullable=False),
    sa.Column('designation', sa.String(length=200), nullable=True),
    sa.Column('area_sqm', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('area_status', sa.Enum('VERIFIED', 'DOCUMENTED', 'OBSERVED', 'DERIVED', 'ESTIMATED', 'INFERRED', 'UNKNOWN', 'CONFLICTING', 'NOT_APPLICABLE', name='land_area_status'), nullable=False),
    sa.Column('area_source_record_id', app.models.base.GUID(), nullable=True),
    sa.Column('land_use_type', sa.String(length=200), nullable=True),
    sa.Column('baulast_status', sa.String(length=40), nullable=False),
    sa.Column('contamination_status', sa.String(length=40), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['area_source_record_id'], ['source_records.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listings',
    sa.Column('property_id', app.models.base.GUID(), nullable=True),
    sa.Column('source_id', app.models.base.GUID(), nullable=False),
    sa.Column('external_listing_id', sa.String(length=300), nullable=True),
    sa.Column('listing_kind', sa.Enum('PURCHASE', 'RENTAL', name='listing_kind'), nullable=False),
    sa.Column('property_type', sa.Enum('CONDOMINIUM_UNIT', 'SINGLE_FAMILY_HOUSE', 'MULTI_FAMILY_HOUSE', 'LAND_PARCEL', 'COMMERCIAL', 'FORECLOSURE', 'OTHER', name='listing_property_type'), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('raw_address_text', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('relisted_from_listing_id', app.models.base.GUID(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['relisted_from_listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_data_points',
    sa.Column('source_record_id', app.models.base.GUID(), nullable=False),
    sa.Column('metric_name', sa.String(length=150), nullable=False),
    sa.Column('value_numeric', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('geographic_zone', sa.String(length=200), nullable=True),
    sa.Column('valuation_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('property_id', app.models.base.GUID(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ownership_structures',
    sa.Column('property_id', app.models.base.GUID(), nullable=False),
    sa.Column('legal_type', sa.String(length=40), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_items',
    sa.Column('property_id', app.models.base.GUID(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_hard_stop', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('building_land_parcels',
    sa.Column('building_id', app.models.base.GUID(), nullable=False),
    sa.Column('land_parcel_id', app.models.base.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['land_parcel_id'], ['land_parcels.id'], ),
    sa.PrimaryKeyConstraint('building_id', 'land_parcel_id')
    )
    op.create_table('deal_analyses',
    sa.Column('property_id', app.models.base.GUID(), nullable=False),
    sa.Column('investment_scenario_id', app.models.base.GUID(), nullable=True),
    sa.Column('all_in_cost_cents', sa.Integer(), nullable=True),
    sa.Column('mao_cents', sa.Integer(), nullable=True),
    sa.Column('deal_status', sa.String(length=30), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investment_scenario_id'], ['investment_scenarios.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('property_id', app.models.base.GUID(), nullable=True),
    sa.Column('listing_id', app.models.base.GUID(), nullable=True),
    sa.Column('document_type', sa.String(length=60), nullable=True),
    sa.Column('original_filename', sa.String(length=300), nullable=True),
    sa.Column('storage_uri', sa.Text(), nullable=True),
    sa.Column('processing_status', sa.String(length=30), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('foreclosure_details',
    sa.Column('listing_id', app.models.base.GUID(), nullable=False),
    sa.Column('court_name', sa.String(length=200), nullable=False),
    sa.Column('case_reference', sa.String(length=100), nullable=False),
    sa.Column('hearing_date', sa.Date(), nullable=True),
    sa.Column('published_verkehrswert_cents', sa.Integer(), nullable=True),
    sa.Column('appraisal_date', sa.Date(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id')
    )
    op.create_table('images',
    sa.Column('property_id', app.models.base.GUID(), nullable=True),
    sa.Column('listing_id', app.models.base.GUID(), nullable=True),
    sa.Column('storage_uri', sa.Text(), nullable=True),
    sa.Column('room_label', sa.String(length=60), nullable=True),
    sa.Column('room_label_confidence', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('land_assessments',
    sa.Column('land_parcel_id', app.models.base.GUID(), nullable=False),
    sa.Column('bodenrichtwert_eur_per_sqm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('bodenrichtwert_zone', sa.String(length=100), nullable=True),
    sa.Column('bodenrichtwert_date', sa.Date(), nullable=True),
    sa.Column('residual_land_value_cents', sa.Integer(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['land_parcel_id'], ['land_parcels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listing_snapshots',
    sa.Column('listing_id', app.models.base.GUID(), nullable=False),
    sa.Column('source_record_id', app.models.base.GUID(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('asking_price_cents', sa.Integer(), nullable=True),
    sa.Column('asking_price_status', sa.Enum('VERIFIED', 'DOCUMENTED', 'OBSERVED', 'DERIVED', 'ESTIMATED', 'INFERRED', 'UNKNOWN', 'CONFLICTING', 'NOT_APPLICABLE', name='asking_price_status'), nullable=False),
    sa.Column('commission_cents', sa.Integer(), nullable=True),
    sa.Column('commission_status', sa.Enum('VERIFIED', 'DOCUMENTED', 'OBSERVED', 'DERIVED', 'ESTIMATED', 'INFERRED', 'UNKNOWN', 'CONFLICTING', 'NOT_APPLICABLE', name='commission_status'), nullable=False),
    sa.Column('commission_notes', sa.Text(), nullable=True),
    sa.Column('living_area_listing_sqm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('land_area_listing_sqm', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rooms_claimed', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('year_built_claimed', sa.Integer(), nullable=True),
    sa.Column('tenancy_status_claimed', sa.Enum('VACANT', 'OWNER_OCCUPIED', 'RENTED', 'PARTIALLY_RENTED', 'UNKNOWN', name='tenancy_status_claimed'), nullable=False),
    sa.Column('description_text', sa.Text(), nullable=True),
    sa.Column('renovation_keyword_hits', app.models.base.JSONVariant(), nullable=True),
    sa.Column('damage_keyword_hits', app.models.base.JSONVariant(), nullable=True),
    sa.Column('conflict_flags', app.models.base.JSONVariant(), nullable=True),
    sa.Column('raw_fields', app.models.base.JSONVariant(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planning_assessments',
    sa.Column('land_parcel_id', app.models.base.GUID(), nullable=False),
    sa.Column('plan_status', sa.String(length=40), nullable=False),
    sa.Column('grz', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('gfz', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('max_floors', sa.Integer(), nullable=True),
    sa.Column('scenario_label', sa.String(length=30), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['land_parcel_id'], ['land_parcels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('units',
    sa.Column('property_id', app.models.base.GUID(), nullable=False),
    sa.Column('building_id', app.models.base.GUID(), nullable=True),
    sa.Column('position_in_building', sa.String(length=30), nullable=True),
    sa.Column('height_position', sa.String(length=30), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('rooms', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('bathrooms', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('living_area_sqm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('living_area_origin', sa.Enum('LISTING', 'VERIFIED_CALCULATION', 'DECLARATION_OF_DIVISION', 'EXPERT_REPORT', 'FLOORPLAN_ESTIMATE', 'USER_INPUT', name='living_area_origin'), nullable=True),
    sa.Column('living_area_status', sa.Enum('VERIFIED', 'DOCUMENTED', 'OBSERVED', 'DERIVED', 'ESTIMATED', 'INFERRED', 'UNKNOWN', 'CONFLICTING', 'NOT_APPLICABLE', name='living_area_status'), nullable=False),
    sa.Column('living_area_source_record_id', app.models.base.GUID(), nullable=True),
    sa.Column('living_area_listing_claim_sqm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('usable_area_sqm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('miteigentumsanteil', sa.String(length=30), nullable=True),
    sa.Column('has_elevator_access', sa.Boolean(), nullable=True),
    sa.Column('has_balcony', sa.Boolean(), nullable=True),
    sa.Column('has_terrace', sa.Boolean(), nullable=True),
    sa.Column('has_cellar', sa.Boolean(), nullable=True),
    sa.Column('has_garden', sa.Boolean(), nullable=True),
    sa.Column('has_parking', sa.Boolean(), nullable=True),
    sa.Column('ownership_structure_id', app.models.base.GUID(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['living_area_source_record_id'], ['source_records.id'], ),
    sa.ForeignKeyConstraint(['ownership_structure_id'], ['ownership_structures.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wegs',
    sa.Column('building_id', app.models.base.GUID(), nullable=True),
    sa.Column('total_units', sa.Integer(), nullable=True),
    sa.Column('reserve_fund_total_cents', sa.Integer(), nullable=True),
    sa.Column('cost_allocation_key_notes', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comparable_sets',
    sa.Column('subject_unit_id', app.models.base.GUID(), nullable=True),
    sa.Column('subject_property_id', app.models.base.GUID(), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'RUNNING', 'COMPLETE', 'PARTIAL', 'BLOCKED', 'FAILED', name='comparable_set_status'), nullable=False),
    sa.Column('search_radius_km_initial', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('search_radius_km_final', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('time_window_months_initial', sa.Integer(), nullable=False),
    sa.Column('time_window_months_final', sa.Integer(), nullable=False),
    sa.Column('expansion_log', app.models.base.JSONVariant(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subject_property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['subject_unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('condition_assessments',
    sa.Column('unit_id', app.models.base.GUID(), nullable=True),
    sa.Column('property_id', app.models.base.GUID(), nullable=True),
    sa.Column('assessed_at', sa.Date(), nullable=True),
    sa.Column('overall_summary', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('damage_cases',
    sa.Column('unit_id', app.models.base.GUID(), nullable=True),
    sa.Column('property_id', app.models.base.GUID(), nullable=True),
    sa.Column('cause', sa.String(length=30), nullable=False),
    sa.Column('cause_status', sa.String(length=20), nullable=False),
    sa.Column('onset_date', sa.Date(), nullable=True),
    sa.Column('is_prior_case', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_extractions',
    sa.Column('document_id', app.models.base.GUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('extracted_field', sa.String(length=150), nullable=True),
    sa.Column('extracted_value', sa.Text(), nullable=True),
    sa.Column('ocr_confidence', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('parser_version', sa.String(length=50), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image_findings',
    sa.Column('image_id', app.models.base.GUID(), nullable=False),
    sa.Column('finding_type', sa.String(length=60), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('is_suspected_only', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leases',
    sa.Column('unit_id', app.models.base.GUID(), nullable=False),
    sa.Column('tenancy_start', sa.Date(), nullable=True),
    sa.Column('net_cold_rent_cents', sa.Integer(), nullable=True),
    sa.Column('rent_mechanism', sa.String(length=30), nullable=True),
    sa.Column('document_id', app.models.base.GUID(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planning_rules',
    sa.Column('planning_assessment_id', app.models.base.GUID(), nullable=False),
    sa.Column('rule_text', sa.Text(), nullable=False),
    sa.Column('rule_type', sa.String(length=60), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['planning_assessment_id'], ['planning_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('renovation_scenarios',
    sa.Column('unit_id', app.models.base.GUID(), nullable=True),
    sa.Column('property_id', app.models.base.GUID(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('target_standard', sa.String(length=100), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rental_assessments',
    sa.Column('unit_id', app.models.base.GUID(), nullable=False),
    sa.Column('current_net_cold_rent_cents', sa.Integer(), nullable=True),
    sa.Column('mietspiegel_indicative_rent_cents', sa.Integer(), nullable=True),
    sa.Column('asking_market_rent_cents', sa.Integer(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('valuation_runs',
    sa.Column('unit_id', app.models.base.GUID(), nullable=True),
    sa.Column('property_id', app.models.base.GUID(), nullable=True),
    sa.Column('valuation_date', sa.Date(), nullable=False),
    sa.Column('model_version_id', app.models.base.GUID(), nullable=True),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('as_is_low_cents', sa.Integer(), nullable=False),
    sa.Column('as_is_base_cents', sa.Integer(), nullable=False),
    sa.Column('as_is_high_cents', sa.Integer(), nullable=False),
    sa.Column('central_value_method', sa.String(length=100), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('confidence_breakdown', app.models.base.JSONVariant(), nullable=False),
    sa.Column('warnings', app.models.base.JSONVariant(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_by', sa.String(length=200), nullable=False),
    sa.Column('trigger', sa.String(length=100), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('supersedes_run_id', app.models.base.GUID(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['supersedes_run_id'], ['valuation_runs.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_valuation_runs_is_current'), 'valuation_runs', ['is_current'], unique=False)
    op.create_table('weg_documents',
    sa.Column('weg_id', app.models.base.GUID(), nullable=False),
    sa.Column('document_id', app.models.base.GUID(), nullable=True),
    sa.Column('document_kind', sa.String(length=60), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['weg_id'], ['wegs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weg_financial_status',
    sa.Column('weg_id', app.models.base.GUID(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.Column('payment_arrears_cents', sa.Integer(), nullable=True),
    sa.Column('outstanding_loans_cents', sa.Integer(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['weg_id'], ['wegs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weg_measures',
    sa.Column('weg_id', app.models.base.GUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('resolution_status', sa.String(length=30), nullable=False),
    sa.Column('estimated_cost_cents', sa.Integer(), nullable=True),
    sa.Column('unit_share_cost_cents', sa.Integer(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['weg_id'], ['wegs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comparables',
    sa.Column('comparable_set_id', app.models.base.GUID(), nullable=False),
    sa.Column('comparable_class', sa.Enum('SOLD_COMPARABLE', 'ASKING_COMPARABLE', 'OFFICIAL_AGGREGATE', name='comparable_class'), nullable=False),
    sa.Column('source_record_id', app.models.base.GUID(), nullable=False),
    sa.Column('external_reference', sa.String(length=300), nullable=True),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('reference_date', sa.Date(), nullable=False),
    sa.Column('living_area_sqm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('condition_label', sa.String(length=60), nullable=True),
    sa.Column('distance_km', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('features', app.models.base.JSONVariant(), nullable=True),
    sa.Column('similarity_breakdown', app.models.base.JSONVariant(), nullable=True),
    sa.Column('similarity_total', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('is_outlier', sa.Boolean(), nullable=False),
    sa.Column('outlier_reason', sa.Text(), nullable=True),
    sa.Column('marketing_duration_days', sa.Integer(), nullable=True),
    sa.Column('was_price_reduced', sa.Boolean(), nullable=True),
    sa.Column('excluded', sa.Boolean(), nullable=False),
    sa.Column('inclusion_reason', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['comparable_set_id'], ['comparable_sets.id'], ),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('component_conditions',
    sa.Column('condition_assessment_id', app.models.base.GUID(), nullable=False),
    sa.Column('component_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('evidence_type', sa.String(length=50), nullable=True),
    sa.Column('derived_action', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['condition_assessment_id'], ['condition_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moisture_measurements',
    sa.Column('damage_case_id', app.models.base.GUID(), nullable=False),
    sa.Column('room', sa.String(length=100), nullable=True),
    sa.Column('measurement_point', sa.String(length=100), nullable=True),
    sa.Column('device', sa.String(length=100), nullable=True),
    sa.Column('method', sa.String(length=100), nullable=True),
    sa.Column('value', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('measured_at', sa.Date(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['damage_case_id'], ['damage_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('renovation_items',
    sa.Column('renovation_scenario_id', app.models.base.GUID(), nullable=False),
    sa.Column('trade', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('unit_price_low_cents', sa.Integer(), nullable=True),
    sa.Column('unit_price_expected_cents', sa.Integer(), nullable=True),
    sa.Column('unit_price_high_cents', sa.Integer(), nullable=True),
    sa.Column('cost_library_item_id', app.models.base.GUID(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cost_library_item_id'], ['cost_library_items.id'], ),
    sa.ForeignKeyConstraint(['renovation_scenario_id'], ['renovation_scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('valuation_method_results',
    sa.Column('valuation_run_id', app.models.base.GUID(), nullable=False),
    sa.Column('method_name', sa.String(length=100), nullable=False),
    sa.Column('value_low_cents', sa.Integer(), nullable=False),
    sa.Column('value_base_cents', sa.Integer(), nullable=False),
    sa.Column('value_high_cents', sa.Integer(), nullable=False),
    sa.Column('weight_used', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('data_quality_notes', sa.Text(), nullable=True),
    sa.Column('comparable_set_id', app.models.base.GUID(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['comparable_set_id'], ['comparable_sets.id'], ),
    sa.ForeignKeyConstraint(['valuation_run_id'], ['valuation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('water_damage_assessments',
    sa.Column('damage_case_id', app.models.base.GUID(), nullable=False),
    sa.Column('known_damage_cost_cents', sa.Integer(), nullable=True),
    sa.Column('expected_hidden_damage_cost_cents', sa.Integer(), nullable=True),
    sa.Column('worst_case_damage_cost_cents', sa.Integer(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['damage_case_id'], ['damage_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('water_damage_assessments')
    op.drop_table('valuation_method_results')
    op.drop_table('renovation_items')
    op.drop_table('moisture_measurements')
    op.drop_table('component_conditions')
    op.drop_table('comparables')
    op.drop_table('weg_measures')
    op.drop_table('weg_financial_status')
    op.drop_table('weg_documents')
    op.drop_index(op.f('ix_valuation_runs_is_current'), table_name='valuation_runs')
    op.drop_table('valuation_runs')
    op.drop_table('rental_assessments')
    op.drop_table('renovation_scenarios')
    op.drop_table('planning_rules')
    op.drop_table('leases')
    op.drop_table('image_findings')
    op.drop_table('document_extractions')
    op.drop_table('damage_cases')
    op.drop_table('condition_assessments')
    op.drop_table('comparable_sets')
    op.drop_table('wegs')
    op.drop_table('units')
    op.drop_table('planning_assessments')
    op.drop_table('listing_snapshots')
    op.drop_table('land_assessments')
    op.drop_table('images')
    op.drop_table('foreclosure_details')
    op.drop_table('documents')
    op.drop_table('deal_analyses')
    op.drop_table('building_land_parcels')
    op.drop_table('risk_items')
    op.drop_table('ownership_structures')
    op.drop_table('notifications')
    op.drop_table('market_data_points')
    op.drop_table('listings')
    op.drop_table('land_parcels')
    op.drop_table('investment_scenarios')
    op.drop_index(op.f('ix_geo_locations_entity_type'), table_name='geo_locations')
    op.drop_index(op.f('ix_geo_locations_entity_id'), table_name='geo_locations')
    op.drop_table('geo_locations')
    op.drop_table('finance_scenarios')
    op.drop_table('due_diligence_items')
    op.drop_index(op.f('ix_data_points_is_current'), table_name='data_points')
    op.drop_index(op.f('ix_data_points_field_name'), table_name='data_points')
    op.drop_index(op.f('ix_data_points_entity_type'), table_name='data_points')
    op.drop_index(op.f('ix_data_points_entity_id'), table_name='data_points')
    op.drop_table('data_points')
    op.drop_table('cost_library_items')
    op.drop_table('buildings')
    op.drop_table('actual_project_results')
    op.drop_table('source_records')
    op.drop_table('source_permissions')
    op.drop_table('properties')
    op.drop_table('sources')
    op.drop_table('model_versions')
    op.drop_table('investment_policies')
    op.drop_index(op.f('ix_audit_log_entity_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('addresses')
    # ### end Alembic commands ###
